[tool.black]
include = 'setup.py$|python\/.*\.pyi?$|python\/punchboot\/.*\.pyi?$'
line-length = 100

[tool.ruff]
line-length = 100
extend-exclude = [
    "src",
    "doc",
    "include",
    "lib",
]

[tool.ruff.lint]
select = ["D"]
exclude = [
    "python/__init__.py",
    "python/punchboot/__init__.py",
    "docs/*.py",
    "setup.py",
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.mypy]
warn_return_any = true
exclude = [
    "^build.*",
    "^docs.*"
]
